### ISSUE TITLE
How to add support for minimizers from another software/library 

### ISSUE THREAD

**Issue by Anders-Markvardsen** [mantidproject/fitbenchmarking#136]
@bb511 I your words how much documentation do we have for helping adding minimizers from another software/library currently and what is missing?

**Comment by bb511** [comment]
@Anders-Markvardsen 
The documentation to adding another software is available here: https://github.com/mantidproject/fitbenchmarking/wiki/Extending
This however provides only an outline. The person who adds the additional software is expected to know some python.
I think the focus should be on making it easier to add a software rather than writing more detailed instructions, since at the moment it is going to be pretty convoluted no matter what.
I suggest that the FitBenchmarking should use some standardised problem definition, since that would make it much more straight forward to both add fitting problems and software.
More on the low priority side, there are some sections of the code where the developer is supposed to add elifs for his software. These should be replaced with some higher level json files or some other alternative, to make it more straightforward and organised (I'll create an issue for this later this week if that is ok).

**Comment by bb511** [comment]
This issue was solved in #136
