### ISSUE TITLE
Neutron Problem GEM 13 IC peaks Fit Warnings

### ISSUE THREAD

**Issue by bb511** [mantidproject/fitbenchmarking#62]
On trying to fit then `GEM 13 IC` neutron problem, the mantid fit algorithm returns this output as a warning, for each minimiser
![image](https://user-images.githubusercontent.com/33397154/43189876-99d6a4f4-8fef-11e8-8598-db317efc3f29.png)

This should be investigated and resolved, as it takes a lot of time for these fits to succeed and these warnings might be the issue.

**Comment by bb511** [comment]
@Anders-Markvardsen Any idea what might be causing this problem or where should I start my search? Thank you.

**Comment by Anders-Markvardsen** [comment]
This warning as it happens is fine and it not the reason for the slowness. This is because IkedaCarpenter is a complex fit function and not surprisingly some minimizers struggle with it.

However, this logging information is from the minimizer software and not the fit-benchmarking code. It would make sense if we channel this information to a separate log file with time stamps.

And discussed above will be dealt with in separate issue on adding logging
